var data1 = JSON.parse(`{
    "Alabama": ["Alexander City", "Andalusia", "Anniston", "Athens", "Atmore", "Auburn", "Bessemer", "Birmingham", "Chickasaw", "Clanton", "Cullman", "Decatur", "Demopolis", "Dothan", "Enterprise", "Eufaula", "Florence", "Fort Payne", "Gadsden", "Greenville", "Guntersville", "Huntsville", "Jasper", "Marion", "Mobile", "Montgomery", "Opelika", "Ozark", "Phenix City", "Prichard", "Scottsboro", "Selma", "Sheffield", "Sylacauga", "Talladega", "Troy", "Tuscaloosa", "Tuscumbia", "Tuskegee"],

    "Alaska": ["Anchorage", "Cordova", "Fairbanks", "Haines", "Homer", "Juneau", "Ketchikan", "Kodiak", "Kotzebue", "Nome", "Palmer", "Seward", "Sitka", "Skagway", "Valdez"],

    "Arizona": ["Ajo", "Avondale", "Bisbee", "Casa Grande", "Chandler", "Clifton", "Douglas", "Flagstaff", "Florence", "Gila Bend", "Glendale", "Globe", "Kingman", "Lake Havasu City", "Mesa", "Nogales", "Oraibi", "Phoenix", "Prescott", "Scottsdale", "Sierra Vista", "Tempe", "Tombstone", "Tucson", "Walpi", "Window Rock", "Winslow", "Yuma"],

    "Arkansas": ["Arkadelphia", "Arkansas Post", "Batesville", "Benton", "Blytheville", "Camden", "Conway", "Crossett", "El Dorado", "Fayetteville", "Forrest City", "Fort Smith", "Harrison", "Helena", "Hope", "Hot Springs", "Jacksonville", "Jonesboro", "Little Rock", "Magnolia", "Morrilton", "Newport", "North Little Rock", "Osceola", "Pine Bluff", "Rogers", "Searcy", "Stuttgart", "Van Buren", "West Memphis"],

    "California": ["Alameda","Alhambra","Anaheim","Antioch","Arcadia","Bakersfield","Barstow","Belmont",    "Berkeley","Beverly Hills","Brea","Buena Park","Burbank","Calexico","Calistoga","Carlsbad","Carmel","Chico","Chula Vista","Claremont","Compton","Concord","Corona","Coronado","Costa Mesa","Culver City","Daly City","Davis","Downey","El Centro","El Cerrito","El Monte","Escondido","Eureka","Fairfield","Fontana","Fremont","Fresno","Fullerton","Garden Grove","Glendale","Hayward","Hollywood","Huntington Beach","Indio","Inglewood","Irvine","La Habra","Laguna Beach","Lancaster","Livermore","Lodi","Lompoc","Long Beach","Los Angeles","Malibu","Martinez","Marysville","Menlo Park","Merced","Modesto","Monterey","Mountain View","Napa","Needles","Newport Beach","Norwalk","Novato","Oakland","Oceanside","Ojai","Ontario","Orange","Oroville","Oxnard","Pacific Grove","Palm Springs","Palmdale","Palo Alto","Pasadena","Petaluma","Pomona","Port Hueneme","Rancho Cucamonga","Red Bluff","Redding","Redlands","Redondo Beach","Redwood City","Richmond","Riverside","Roseville","Sacramento","Salinas","San Bernardino","San Clemente","San Diego","San Fernando","San Francisco","San Gabriel","San Jose","San Juan Capistrano","San Leandro","San Luis Obispo","San Marino","San Mateo","San Pedro","San Rafael","San Simeon","Santa Ana","Santa Barbara","Santa Clara","Santa Clarita","Santa Cruz","Santa Monica","Santa Rosa","Sausalito","Simi Valley","Sonoma","South San Francisco","Stockton","Sunnyvale","Susanville","Thousand Oaks","Torrance","Turlock","Ukiah","Vallejo","Ventura","Victorville","Visalia","Walnut Creek","Watts","West Covina","Whittier","Woodland","Yorba Linda","Yuba City"],

        "Colorado": ["Alamosa","Aspen","Aurora","Boulder","Breckenridge","Brighton","Canon City","Central City","Climax","Colorado Springs","Cortez","Cripple Creek","Denver","Durango","Englewood","Estes Park","Fort Collins","Fort Morgan","Georgetown","Glenwood Springs","Golden","Grand Junction","Greeley","Gunnison","La Junta","Leadville","Littleton","Longmont","Loveland","Montrose","Ouray","Pagosa Springs","Pueblo","Silverton","Steamboat Springs","Sterling","Telluride","Trinidad","Vail","Walsenburg","Westminster"],

        "Connecticut": ["Ansonia","Berlin","Bloomfield","Branford","Bridgeport","Bristol","Coventry","Danbury","Darien","Derby","East Hartford","East Haven","Enfield","Fairfield","Farmington","Greenwich","Groton","Guilford","Hamden","Hartford","Lebanon","Litchfield","Manchester","Mansfield","Meriden","Middletown","Milford","Mystic","Naugatuck","New Britain","New Haven","New London","North Haven","Norwalk","Norwich","Old Saybrook","Orange","Seymour","Shelton","Simsbury","Southington","Stamford","Stonington","Stratford","Torrington","Wallingford","Waterbury","Waterford","Watertown","West Hartford","West Haven","Westport","Wethersfield","Willimantic","Windham","Windsor","Windsor Locks","Winsted"],

        "Delaware": ["Dover", "Lewes", "Milford", "New Castle", "Newark", "Smyrna", "Wilmington"],
        "Florida": ["Apalachicola","Bartow","Belle Glade","Boca Raton","Bradenton","Cape Coral","Clearwater","Cocoa Beach","Cocoa-Rockledge","Coral Gables","Daytona Beach","De Land","Deerfield Beach","Delray Beach","Fernandina Beach","Fort Lauderdale","Fort Myers","Fort Pierce","Fort Walton Beach","Gainesville","Hallandale Beach","Hialeah","Hollywood","Homestead","Jacksonville","Key West","Lake City","Lake Wales","Lakeland","Largo","Melbourne","Miami","Miami Beach","Naples","New Smyrna Beach","Ocala","Orlando","Ormond Beach","Palatka","Palm Bay","Palm Beach","Panama City","Pensacola","Pompano Beach","Saint Augustine","Saint Petersburg","Sanford","Sarasota","Sebring","Tallahassee","Tampa","Tarpon Springs","Titusville","Venice","West Palm Beach","White Springs","Winter Haven","Winter Park"],

        "Georgia": ["Albany","Americus","Andersonville","Athens","Atlanta","Augusta","Bainbridge","Blairsville","Brunswick","Calhoun","Carrollton","Columbus","Dahlonega","Dalton","Darien","Decatur","Douglas","East Point","Fitzgerald","Fort Valley","Gainesville","La Grange","Macon","Marietta","Milledgeville","Plains","Rome","Savannah","Toccoa","Valdosta","Warm Springs","Warner Robins","Washington","Waycross"],

        "Hawaii": ["Hanalei","Hilo","Honaunau","Honolulu","Kahului","Kaneohe","Kapaa","Kawaihae","Lahaina","Laie","Wahiawa","Wailuku","Waimea"],

        "Idaho": ["Blackfoot","Boise","Bonners Ferry","Caldwell","Coeur d’Alene","Idaho City","Idaho Falls","Kellogg","Lewiston","Moscow","Nampa","Pocatello","Priest River","Rexburg","Sun Valley","Twin Falls"],

        "Illinois": ["Alton","Arlington Heights","Arthur","Aurora","Belleville","Belvidere","Bloomington","Brookfield","Cahokia","Cairo","Calumet City","Canton","Carbondale","Carlinville","Carthage","Centralia","Champaign","Charleston","Chester","Chicago","Chicago Heights","Cicero","Collinsville","Danville","Decatur","DeKalb","Des Plaines","Dixon","East Moline","East Saint Louis","Effingham","Elgin","Elmhurst","Evanston","Freeport","Galena","Galesburg","Glen Ellyn","Glenview","Granite City","Harrisburg","Herrin","Highland Park","Jacksonville","Joliet","Kankakee","Kaskaskia","Kewanee","La Salle","Lake Forest","Libertyville","Lincoln","Lisle","Lombard","Macomb","Mattoon","Moline","Monmouth","Mount Vernon","Mundelein","Naperville","Nauvoo","Normal","North Chicago","Oak Park","Oregon","Ottawa","Palatine","Park Forest","Park Ridge","Pekin","Peoria","Petersburg","Pontiac","Quincy","Rantoul","River Forest","Rock Island","Rockford","Salem","Shawneetown","Skokie","South Holland","Springfield","Streator","Summit","Urbana","Vandalia","Virden","Waukegan","Wheaton","Wilmette","Winnetka","Wood River","Zion"],

        "Indiana": ["Anderson","Bedford","Bloomington","Columbus","Connersville","Corydon","Crawfordsville","East Chicago","Elkhart","Elwood","Evansville","Fort Wayne","French Lick","Gary","Geneva","Goshen","Greenfield","Hammond","Hobart","Huntington","Indianapolis","Jeffersonville","Kokomo","Lafayette","Madison","Marion","Michigan City","Mishawaka","Muncie","Nappanee","Nashville","New Albany","New Castle","New Harmony","Peru","Plymouth","Richmond","Santa Claus","Shelbyville","South Bend","Terre Haute","Valparaiso","Vincennes","Wabash","West Lafayette"],

        "Iowa": ["Amana Colonies","Ames","Boone","Burlington","Cedar Falls","Cedar Rapids","Charles City","Cherokee","Clinton","Council Bluffs","Davenport","Des Moines","Dubuque","Estherville","Fairfield","Fort Dodge","Grinnell","Indianola","Iowa City","Keokuk","Mason City","Mount Pleasant","Muscatine","Newton","Oskaloosa","Ottumwa","Sioux City","Waterloo","Webster City","West Des Moines"],

        "Kansas": ["Abilene","Arkansas City","Atchison","Chanute","Coffeyville","Council Grove","Dodge City","Emporia","Fort Scott","Garden City","Great Bend","Hays","Hutchinson","Independence","Junction City","Kansas City","Lawrence","Leavenworth","Liberal","Manhattan","McPherson","Medicine Lodge","Newton","Olathe","Osawatomie","Ottawa","Overland Park","Pittsburg","Salina","Shawnee","Smith Center","Topeka","Wichita"],

        "Kentucky": ["Ashland","Barbourville","Bardstown","Berea","Boonesborough","Bowling Green","Campbellsville","Covington","Danville","Elizabethtown","Frankfort","Harlan","Harrodsburg","Hazard","Henderson","Hodgenville","Hopkinsville","Lexington","Louisville","Mayfield","Maysville","Middlesboro","Newport","Owensboro","Paducah","Paris","Richmond"],

        "Louisiana": ["Abbeville","Alexandria","Bastrop","Baton Rouge","Bogalusa","Bossier City","Gretna","Houma","Lafayette","Lake Charles","Monroe","Morgan City","Natchitoches","New Iberia","New Orleans","Opelousas","Ruston","Saint Martinville","Shreveport","Thibodaux"],

        "Maine": ["Auburn","Augusta","Bangor","Bar Harbor","Bath","Belfast","Biddeford","Boothbay Harbor","Brunswick","Calais","Caribou","Castine","Eastport","Ellsworth","Farmington","Fort Kent","Gardiner","Houlton","Kennebunkport","Kittery","Lewiston","Lubec","Machias","Orono","Portland","Presque Isle","Rockland","Rumford","Saco","Scarborough","Waterville","York"],

        "Maryland": ["Aberdeen","Annapolis","Baltimore","Bethesda-Chevy Chase","Bowie","Cambridge","Catonsville","College Park","Columbia","Cumberland","Easton","Elkton","Emmitsburg","Frederick","Greenbelt","Hagerstown","Hyattsville","Laurel","Oakland","Ocean City","Rockville","Saint Marys City","Salisbury","Silver Spring","Takoma Park","Towson","Westminster"],

        "Massachusetts": ["Abington","Adams","Amesbury","Amherst","Andover","Arlington","Athol","Attleboro","Barnstable","Bedford","Beverly","Boston","Bourne","Braintree","Brockton","Brookline","Cambridge","Canton","Charlestown","Chelmsford","Chelsea","Chicopee","Clinton","Cohasset","Concord","Danvers","Dartmouth","Dedham","Dennis","Duxbury","Eastham","Edgartown","Everett","Fairhaven","Fall River","Falmouth","Fitchburg","Framingham","Gloucester","Great Barrington","Greenfield","Groton","Harwich","Haverhill","Hingham","Holyoke","Hyannis","Ipswich","Lawrence","Lenox","Leominster","Lexington","Lowell","Ludlow","Lynn","Malden","Marblehead","Marlborough","Medford","Milton","Nahant","Natick","New Bedford","Newburyport","Newton","North Adams","Northampton","Norton","Norwood","Peabody","Pittsfield","Plymouth","Provincetown","Quincy","Randolph","Revere","Salem","Sandwich","Saugus","Somerville","South Hadley","Springfield","Stockbridge","Stoughton","Sturbridge","Sudbury","Taunton","Tewksbury","Truro","Watertown","Webster","Wellesley","Wellfleet","West Bridgewater","West Springfield","Westfield","Weymouth","Whitman","Williamstown","Woburn","Woods Hole","Worcester"],

        "Michigan": ["Adrian","Alma","Ann Arbor","Battle Creek","Bay City","Benton Harbor","Bloomfield Hills","Cadillac","Charlevoix","Cheboygan","Dearborn","Detroit","East Lansing","Eastpointe","Ecorse","Escanaba","Flint","Grand Haven","Grand Rapids","Grayling","Grosse Pointe","Hancock","Highland Park","Holland","Houghton","Interlochen","Iron Mountain","Ironwood","Ishpeming","Jackson","Kalamazoo","Lansing","Livonia","Ludington","Mackinaw City","Manistee","Marquette","Menominee","Midland","Monroe","Mount Clemens","Mount Pleasant","Muskegon","Niles","Petoskey","Pontiac","Port Huron","Royal Oak","Saginaw","Saint Ignace","Saint Joseph","Sault Sainte Marie","Traverse City","Trenton","Warren","Wyandotte","Ypsilanti"]
        
}`)

export default data1